# Generated by Django 5.0.6 on 2024-06-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_rating_order_orderitem_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imgage',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
