# Generated by Django 5.0.6 on 2024-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderitem_image_product_imgage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
