# Generated by Django 5.0.6 on 2024-06-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgage',
            new_name='image',
        ),
    ]
