# Generated by Django 5.0.6 on 2024-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_user_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default-product-image.png', null=True, upload_to=''),
        ),
    ]
